# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "282f8a7dac177dea83cd4218204c7096"
name = "simple-discount-app"
handle = "simple-discount-app-2"
application_url = "https://bathroom-lamps-shopping-accommodations.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts, write_discounts_allocator_functions, write_price_rules,read_price_rules,read_products"

[auth]
redirect_urls = [
  "https://bathroom-lamps-shopping-accommodations.trycloudflare.com/auth/callback",
  "https://bathroom-lamps-shopping-accommodations.trycloudflare.com/auth/shopify/callback",
  "https://bathroom-lamps-shopping-accommodations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "store-for-returns.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
